import type { Metadata } from "next";
import {  Roboto
} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'

import { cn } from "@/lib/utils"
import AppCartProvider from "@/components/shop/app-cart-privider";
import { Toaster } from "@/components/ui/toaster"
import Footer from "@/components/layout/footer";
import { SessionProvider } from "next-auth/react";
import { ptBR } from "@clerk/localizations";

   
export const metadata: Metadata = {
  title: "Stilo20",
  description: "Generated by create next app",
};
const cormot = Roboto ({weight:[ '400','500','900','700' ],subsets:['latin']})
 
 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(cormot.className, "min-h-screen   bg-pink-100 flex flex-col")}>
        <AppCartProvider >
          <ClerkProvider localization={ptBR}>
            <SessionProvider>
              <Toaster />
              <main
                className={"flex-grow transition duration-3000 ease-in-out"}
              >
                {children}
              </main>
          
            </SessionProvider>
          </ClerkProvider>
          :
        </AppCartProvider>
      </body>
    </html>
  );
}
