import type { Metadata } from "next";
import { Inter, Oxygen } from "next/font/google";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
 
import { cn } from "@/lib/utils"
import Header from "@/components/layout/header";
import AppCartProvider from "@/components/shop/app-cart-privider";
import { Toaster } from "@/components/ui/toaster"

  const inter = Inter({ subsets: ["latin"] });
const oxygem = Oxygen({weight:['300','400','700'],subsets:['latin']})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 
 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(oxygem.className, "min-h-screen flex flex-col")}>
        <AppCartProvider>
          <Header />
          <Toaster />

          <main className="flex-grow">{children}</main>
        </AppCartProvider>
      </body>
    </html>
  );
}
