import type { Metadata } from "next";
import { Inter, Alfa_Slab_One, Concert_One } from "next/font/google";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
 
import { cn } from "@/lib/utils"
import Header from "@/components/layout/header";
import AppCartProvider from "@/components/shop/app-cart-privider";
import { Toaster } from "@/components/ui/toaster"
import Footer from "@/components/layout/footer";
import Products from "./products-highlights/page";
import Map from "@/components/layout/map";
 
 const alfa_Slab_One = Alfa_Slab_One({weight:[ '400'],subsets:['latin']})

 const cormot = Concert_One({weight:[ '400'],subsets:['latin']})
//  '500', '600','700'
export const metadata: Metadata = {
  title: "Stilo20",
  description: "Generated by create next app",
 icons:"./assets/412762104_700966975471907_1046785583651790907_n.jpg"
};

 
 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(cormot.className, "min-h-screen flex flex-col")}>
        <AppCartProvider>
          <Header />
          <Toaster />
          <main  className={cn(alfa_Slab_One.className, "flex-grow")}>{children}</main>
          <Products/>
          <Map/>
          <Footer/>
        </AppCartProvider>
      </body>
    </html>
  );
}
